version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
  johnnydemo.api:
    image: ${DOCKER_REGISTRY-}johnnydemoapi
    build:
      context: .
      dockerfile: JohnnyDemo.Api/Dockerfile
    depends_on:
      - sqldata
